server:
  port: 8080

routes:
  - path: /api/users
    target:
      - http://localhost:3001
      - http://localhost:3002

  - path: /api/orders
    target:
      - http://localhost:4002
  - path: /api/users/pages
    target:
      - http://localhost:4003
